name: Test

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        elixir: [1.17, 1.18]
        otp: [25, 27]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile test env
        run: mix compile --warnings-as-errors
        env:
          MIX_ENV: test

      - name: Run tests
        run: mix test
